### ISSUE TITLE
Bug Imposible à lancer plugin introuvable

### ISSUE THREAD

**Issue by Mickael64121** [tuxgasy/jeedom-tydom#10]
Bonjour, 
Lors de la mise en place du zip sur mon jeedom atlas il me dit plugin introuvable. pouvez vous m'aider ?
![Capture d’écran 2023-11-23 184228](https://github.com/tuxgasy/jeedom-tydom/assets/151868713/59e6af47-789d-408d-8f3b-d429b2b73edb)

**Comment by tuxgasy** [comment]
Bonjour,
Le dossier du plugin doit être tydom (sans le "jeedom-" au début).
Si plus simple, le module est disponible en beta sur le market.

**Comment by Mickael64121** [comment]
Bonsoir.

Super rapide votre reponse....


Sur le market jeedom ? Je ne vous pas le beta. J ai du oublié d activé une
option


Le jeu. 23 nov. 2023, 19:22, Garcia MICHEL ***@***.***> a
écrit :

**Comment by tuxgasy** [comment]
Il faut activer l'accès aux plugins beta dans votre profil Jeedom Market.

**Comment by Mickael64121** [comment]
Merci, je vais le tester.
